In [79]:
# Import Dependencies
import numpy as np
import matplotlib.pyplot as plt
import io
import pandas as pd
import os
from collections import Counter

In [7]:
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import RandomOverSampler
from sklearn.linear_model import LogisticRegression
from imblearn.over_sampling import SMOTE

In [11]:
data_2 = r'/Users/dang/Documents/Bootcamp/UNC_Analytics_Bootcamp_Capstone_2022/Data/'
df = pd.read_csv(os.path.join(data_2,'complete_joined_all.csv'))
df.head()

,state,animal_id,age,sex,animal_type,breed_class,weight_lbs,temperature,heart_rate_bpm,resp_rate_bpm,...,ixodes_scapularis_county_status_2016,ixodes_pacificus_county_status_2016,ixodes_scapularis_county_status_2018,ixodes_pacificus_county_status_2018,ixodes_scapularis_county_status_2019,ixodes_pacificus_county_status_2019,ixodes_scapularis_county_status_2020,ixodes_pacificus_county_status_2020,ixodes_scapularis_county_status_2021,ixodes_pacificus_county_status_2021
0,TX,A666651,12 years,Spayed Female,Dog,Medium,26.0,101.0,141.0,59.0,...,Established,No records,Established,No records,Established,No records,Established,No records,Established,No records
1,TX,A666651,12 years,Spayed Female,Dog,Medium,26.0,101.0,141.0,59.0,...,Established,No records,Established,No records,Established,No records,Established,No records,Established,No records
2,TX,A666651,12 years,Spayed Female,Dog,Medium,26.0,101.0,141.0,59.0,...,No records,No records,No records,No records,No records,No records,No records,No records,No records,No records
3,TX,A666651,12 years,Spayed Female,Dog,Medium,26.0,101.0,141.0,59.0,...,No records,No records,No records,No records,No records,No records,No records,No records,No records,No records
4,TX,A666651,12 years,Spayed Female,Dog,Medium,26.0,101.0,141.0,59.0,...,No records,No records,No records,No records,No records,No records,No records,No records,No records,No records

In [14]:
data_2 = r'/Users/dang/Documents/Bootcamp/UNC_Analytics_Bootcamp_Capstone_2022/Data/'
Animal_Data_df = pd.read_csv(os.path.join(data_2,'updated_animal_data1.csv'))
Animal_Data_df.head()

,animal_id,state,age,sex,animal_type,breed_class,color,weight_lbs,temperature,heart_rate_bpm,...,vomiting,diarrhea,inappetence,lethargic,lameness,muscle_pain,joint_swelling,reported_weight_loss,skin_condition,is_4dx_tested
0,A803419,TX,2 years,Intact Male,Dog,Small,Black/White,7,101,146,...,None,None,Mild,Moderate,None,Mild,None,None,Normal,Not Tested
1,A800463,TX,7 months,Intact Female,Dog,Medium,Tan/Black,45,102,116,...,Mild,Mild,Mild,None,None,None,None,None,Irritation,Not Tested
2,A803414,TX,2 years,Intact Female,Dog,Large,Black/Tricolor,63,102,161,...,Mild,None,None,Moderate,None,None,None,None,Normal,Not Tested
3,A803417,TX,1 month,Intact Female,Dog,Medium,Brown/Tan,39,101,129,...,Mild,Mild,None,Moderate,Present,None,None,None,Bruising,Not Tested
4,A803412,TX,5 months,Intact Male,Dog,Small,Brown/Black,21,102,165,...,None,None,None,Moderate,None,None,None,None,Normal,Not Tested

In [16]:
# checking columns and data types
Animal_Data_df.dtypes

animal_id               object
state                   object
age                     object
sex                     object
animal_type             object
breed_class             object
color                   object
weight_lbs               int64
temperature              int64
heart_rate_bpm           int64
resp_rate_bpm            int64
mm                      object
crt                     object
mentation               object
vomiting                object
diarrhea                object
inappetence             object
lethargic               object
lameness                object
muscle_pain             object
joint_swelling          object
reported_weight_loss    object
skin_condition          object
is_4dx_tested           object
dtype: object

## Preprocessing data for supervised learning

In [17]:
#Drop the unnecessary columns 
clean_animal_data_df= Animal_Data_df.drop(['animal_id', 'state', 'sex', 'animal_type', 'breed_class', 'color'], axis=1)
clean_animal_data_df.head()

,age,weight_lbs,temperature,heart_rate_bpm,resp_rate_bpm,mm,crt,mentation,vomiting,diarrhea,inappetence,lethargic,lameness,muscle_pain,joint_swelling,reported_weight_loss,skin_condition,is_4dx_tested
0,2 years,7,101,146,137,Pale,UTO,BAR,None,None,Mild,Moderate,None,Mild,None,None,Normal,Not Tested
1,7 months,45,102,116,38,Light Pink,>2 sec,Dull/Depressed,Mild,Mild,Mild,None,None,None,None,None,Irritation,Not Tested
2,2 years,63,102,161,44,Pink,1-2 sec,BAR,Mild,None,None,Moderate,None,None,None,None,Normal,Not Tested
3,1 month,39,101,129,49,Pink,1-2 sec,BAR,Mild,Mild,None,Moderate,Present,None,None,None,Bruising,Not Tested
4,5 months,21,102,165,128,Pale,UTO,QAR,None,None,None,Moderate,None,None,None,None,Normal,Not Tested

In [36]:
#Check the status of column ['is_4dx_tasted'] 
clean_animal_data_df['is_4dx_tested'].value_counts()

Not Tested    32530
Negative      14853
Positive       2126
Name: is_4dx_tested, dtype: int64

In [48]:
test_df = clean_animal_data_df.loc[clean_animal_data_df['is_4dx_tested'] != 'Not Tested']
test_df

,age,weight_lbs,temperature,heart_rate_bpm,resp_rate_bpm,mm,crt,mentation,vomiting,diarrhea,inappetence,lethargic,lameness,muscle_pain,joint_swelling,reported_weight_loss,skin_condition,is_4dx_tested
6,1 year,15,102,183,44,Pink,1-2 sec,QAR,Mild,Mild,None,None,None,None,None,None,Normal,Negative
8,2 years,72,100,138,21,Pink,>2 sec,QAR,Mild,None,None,None,None,None,None,Present,Normal,Negative
10,2 days,63,102,160,50,Pink,1-2 sec,QAR,None,None,Mild,None,None,None,None,None,Normal,Negative
11,2 days,59,102,157,18,Pink,>2 sec,Dull/Depressed,Mild,Mild,Moderate,None,None,None,Mild,None,Normal,Negative
19,6 years,42,104,110,40,Light Pink,1-2 sec,Dull/Depressed,None,Moderate,Mild,None,None,Mild,Mild,None,Normal,Positive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49490,1 year,63,104,137,142,Pink,1-2 sec,BAR,Mild,Mild,Mild,Moderate,None,Moderate,Mild,None,Normal,Positive
49494,2 years,55,101,146,126,Pale,UTO,Obtunded,Moderate,Chronic,Moderate,None,None,None,None,None,Normal,Negative
49497,1 year,23,101,145,60,Pink,1-2 sec,Dull/Depressed,None,Mild,Mild,None,None,None,None,None,Normal,Negative
49500,5 years,66,103,185,120,Light Pink,<1 sec,Dull/Depressed,None,None,Mild,None,None,Moderate,Moderate,None,Normal,Positive
49502,1 year,49,100,175,42,Pink,1-2 sec,Dull/Depressed,Mild,Moderate,None,Mild,None,Mild,None,None,Normal,Negative

In [50]:
test_df['is_4dx_tested'].value_counts()

Negative    14853
Positive     2126
Name: is_4dx_tested, dtype: int64

In [60]:
#Converting the age column to just numbers - years
# First, splitting the column into two new colummns - one for number and the other for the string (years, months, etc.)
test_df[['age_num', 'age_str']] = test_df['age'].apply(lambda x: pd.Series(str(x).split(" ")))

# Setting the original age column equal to the age_num column - i.e. changing the data in the age column to just the numbers
test_df['age'] = test_df['age_num']

# Changing the data type of the age column to float
test_df['age'] = test_df['age'].astype('float')

/Users/dang/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/pandas/core/frame.py:3641: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]
/Users/dang/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/Users/dang/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':

In [62]:
# Checking the column to see what the unique string values are
test_df["age_str"].unique()

array(['year', 'years', 'days', 'months', 'month', 'weeks', 'week', 'day'],
      dtype=object)

In [63]:
# Using the string column to change the number value - converting all ages to years
test_df.loc[test_df.age_str == 'days', ['age']] = test_df['age'] / 365
test_df.loc[test_df.age_str == 'day', ['age']] = test_df['age'] / 365
test_df.loc[test_df.age_str == 'months', ['age']] = test_df['age'] / 12
test_df.loc[test_df.age_str == 'month', ['age']] = test_df['age'] / 12
test_df.loc[test_df.age_str == 'weeks', ['age']] = test_df['age'] / 52
test_df.loc[test_df.age_str == 'week', ['age']] = test_df['age'] / 52

print(test_df.shape)
test_df.head()

(16979, 20)

/Users/dang/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/pandas/core/indexing.py:1835: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value[:, i].tolist(), pi)

,age,weight_lbs,temperature,heart_rate_bpm,resp_rate_bpm,mm,crt,mentation,vomiting,diarrhea,inappetence,lethargic,lameness,muscle_pain,joint_swelling,reported_weight_loss,skin_condition,is_4dx_tested,age_num,age_str
6,1.000000,15,102,183,44,Pink,1-2 sec,QAR,Mild,Mild,None,None,None,None,None,None,Normal,Negative,1,year
8,2.000000,72,100,138,21,Pink,>2 sec,QAR,Mild,None,None,None,None,None,None,Present,Normal,Negative,2,years
10,0.005479,63,102,160,50,Pink,1-2 sec,QAR,None,None,Mild,None,None,None,None,None,Normal,Negative,2,days
11,0.005479,59,102,157,18,Pink,>2 sec,Dull/Depressed,Mild,Mild,Moderate,None,None,None,Mild,None,Normal,Negative,2,days
19,6.000000,42,104,110,40,Light Pink,1-2 sec,Dull/Depressed,None,Moderate,Mild,None,None,Mild,Mild,None,Normal,Positive,6,years

In [64]:
# Dropping the extra (created) columns - age_num and age_str
prep_animalData_df = test_df.drop(['age_str', 'age_num'], axis=1)
print(prep_animalData_df.columns)
print(prep_animalData_df.dtypes)
print(prep_animalData_df.shape)
prep_animalData_df.head()

Index(['age', 'weight_lbs', 'temperature', 'heart_rate_bpm', 'resp_rate_bpm',
       'mm', 'crt', 'mentation', 'vomiting', 'diarrhea', 'inappetence',
       'lethargic', 'lameness', 'muscle_pain', 'joint_swelling',
       'reported_weight_loss', 'skin_condition', 'is_4dx_tested'],
      dtype='object')
age                     float64
weight_lbs                int64
temperature               int64
heart_rate_bpm            int64
resp_rate_bpm             int64
mm                       object
crt                      object
mentation                object
vomiting                 object
diarrhea                 object
inappetence              object
lethargic                object
lameness                 object
muscle_pain              object
joint_swelling           object
reported_weight_loss     object
skin_condition           object
is_4dx_tested            object
dtype: object
(16979, 18)

,age,weight_lbs,temperature,heart_rate_bpm,resp_rate_bpm,mm,crt,mentation,vomiting,diarrhea,inappetence,lethargic,lameness,muscle_pain,joint_swelling,reported_weight_loss,skin_condition,is_4dx_tested
6,1.000000,15,102,183,44,Pink,1-2 sec,QAR,Mild,Mild,None,None,None,None,None,None,Normal,Negative
8,2.000000,72,100,138,21,Pink,>2 sec,QAR,Mild,None,None,None,None,None,None,Present,Normal,Negative
10,0.005479,63,102,160,50,Pink,1-2 sec,QAR,None,None,Mild,None,None,None,None,None,Normal,Negative
11,0.005479,59,102,157,18,Pink,>2 sec,Dull/Depressed,Mild,Mild,Moderate,None,None,None,Mild,None,Normal,Negative
19,6.000000,42,104,110,40,Light Pink,1-2 sec,Dull/Depressed,None,Moderate,Mild,None,None,Mild,Mild,None,Normal,Positive

In [73]:
# Creating features
X = test_df.drop(columns='is_4dx_tested')
X = pd.get_dummies(X)

#Find A Target
y = test_df['is_4dx_tested']

X.head(2)

,age,weight_lbs,temperature,heart_rate_bpm,resp_rate_bpm,mm_Light Pink,mm_Pale,mm_Pink,crt_1-2 sec,crt_<1 sec,...,age_num_8,age_num_9,age_str_day,age_str_days,age_str_month,age_str_months,age_str_week,age_str_weeks,age_str_year,age_str_years
6,1.0,15,102,183,44,0,0,1,1,0,...,0,0,0,0,0,0,0,0,1,0
8,2.0,72,100,138,21,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1

In [74]:
X.describe()

,age,weight_lbs,temperature,heart_rate_bpm,resp_rate_bpm,mm_Light Pink,mm_Pale,mm_Pink,crt_1-2 sec,crt_<1 sec,...,age_num_8,age_num_9,age_str_day,age_str_days,age_str_month,age_str_months,age_str_week,age_str_weeks,age_str_year,age_str_years
count,16979.000000,16979.000000,16979.000000,16979.000000,16979.000000,16979.000000,16979.000000,16979.000000,16979.000000,16979.000000,...,16979.000000,16979.000000,16979.000000,16979.000000,16979.000000,16979.000000,16979.000000,16979.000000,16979.000000,16979.000000
mean,2.677442,52.787738,100.941987,138.631898,65.820779,0.129218,0.139996,0.730785,0.479298,0.211909,...,0.037753,0.033865,0.002827,0.006420,0.055598,0.208728,0.002827,0.015372,0.193121,0.515107
std,3.062319,31.285347,1.586213,29.759678,44.605111,0.335451,0.346994,0.443565,0.499586,0.408673,...,0.190603,0.180888,0.053096,0.079868,0.229151,0.406412,0.053096,0.123031,0.394759,0.499786
min,0.000000,5.000000,99.000000,88.000000,18.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.666667,29.000000,100.000000,113.000000,32.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2.000000,51.000000,101.000000,138.000000,47.000000,0.000000,0.000000,1.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,4.000000,73.000000,102.000000,164.000000,123.000000,0.000000,0.000000,1.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
max,20.000000,200.000000,105.000000,190.000000,150.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [75]:
y.value_counts()

Negative    14853
Positive     2126
Name: is_4dx_tested, dtype: int64

## Split our data into training and testing

In [88]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [89]:
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Random Oversampling

In [90]:
ros = RandomOverSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)

Counter(y_resampled)

Counter({'Negative': 11177, 'Positive': 11177})

In [91]:
# Train the Logistic Regression model using the resampled data

lr_model = LogisticRegression(solver='lbfgs', random_state=42)
lr_model.fit(X_resampled, y_resampled)

/Users/dang/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

LogisticRegression(random_state=42)

In [93]:
y_pred = lr_model.predict(X_test)
print(str('Random Oversampling'))
print(str('Balanced Accuracy Score'))
print(balanced_accuracy_score(y_test, y_pred))

Random Oversampling
Balanced Accuracy Score
0.9675367796814371

In [94]:
# Display the confusion matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
cm_df = pd.DataFrame(confusion_matrix, index=["Actual Negative", "Actual Positive"], columns=["Predicted Negative", "Predicted Positive"])
cm_df

                 Predicted Negative  Predicted Positive
Actual Negative                3573                 103
Actual Positive                  21                 548

In [96]:
# Print the imbalanced classification report
#print(str('Random Oversampling'))
#print(str('Imbalanced Classification Report'))
#print(classification_report_imbalanced(y_test, y_pred))
report_df = pd.DataFrame(classification_report_imbalanced(y_test, y_pred, output_dict=True)).transpose()
report_df

,pre,rec,spe,f1,geo,iba,sup
Negative,0.994157,0.971980,0.963093,0.982944,0.967527,0.936940,3676.000000
Positive,0.841782,0.963093,0.971980,0.898361,0.967527,0.935276,569.000000
avg_pre,0.973733,0.973733,0.973733,0.973733,0.973733,0.973733,0.973733
avg_rec,0.970789,0.970789,0.970789,0.970789,0.970789,0.970789,0.970789
avg_spe,0.964284,0.964284,0.964284,0.964284,0.964284,0.964284,0.964284
avg_f1,0.971606,0.971606,0.971606,0.971606,0.971606,0.971606,0.971606
avg_geo,0.967527,0.967527,0.967527,0.967527,0.967527,0.967527,0.967527
avg_iba,0.936717,0.936717,0.936717,0.936717,0.936717,0.936717,0.936717
total_support,4245.000000,4245.000000,4245.000000,4245.000000,4245.000000,4245.000000,4245.000000

## Random Forest

In [114]:
df2 = test_df.drop(['age_str', 'age_num'], axis=1)

df2.head()

,age,weight_lbs,temperature,heart_rate_bpm,resp_rate_bpm,mm,crt,mentation,vomiting,diarrhea,inappetence,lethargic,lameness,muscle_pain,joint_swelling,reported_weight_loss,skin_condition,is_4dx_tested
6,1.000000,15,102,183,44,Pink,1-2 sec,QAR,Mild,Mild,None,None,None,None,None,None,Normal,Negative
8,2.000000,72,100,138,21,Pink,>2 sec,QAR,Mild,None,None,None,None,None,None,Present,Normal,Negative
10,0.005479,63,102,160,50,Pink,1-2 sec,QAR,None,None,Mild,None,None,None,None,None,Normal,Negative
11,0.005479,59,102,157,18,Pink,>2 sec,Dull/Depressed,Mild,Mild,Moderate,None,None,None,Mild,None,Normal,Negative
19,6.000000,42,104,110,40,Light Pink,1-2 sec,Dull/Depressed,None,Moderate,Mild,None,None,Mild,Mild,None,Normal,Positive

In [115]:
def change_string(is_4dx_tested):
    if is_4dx_tested == 'Positive':
        return 1
    else:
        return 0

df2['is_4dx_tested'] = df2['is_4dx_tested'].apply(change_string) 
df2.head(5)

,age,weight_lbs,temperature,heart_rate_bpm,resp_rate_bpm,mm,crt,mentation,vomiting,diarrhea,inappetence,lethargic,lameness,muscle_pain,joint_swelling,reported_weight_loss,skin_condition,is_4dx_tested
6,1.000000,15,102,183,44,Pink,1-2 sec,QAR,Mild,Mild,None,None,None,None,None,None,Normal,0
8,2.000000,72,100,138,21,Pink,>2 sec,QAR,Mild,None,None,None,None,None,None,Present,Normal,0
10,0.005479,63,102,160,50,Pink,1-2 sec,QAR,None,None,Mild,None,None,None,None,None,Normal,0
11,0.005479,59,102,157,18,Pink,>2 sec,Dull/Depressed,Mild,Mild,Moderate,None,None,None,Mild,None,Normal,0
19,6.000000,42,104,110,40,Light Pink,1-2 sec,Dull/Depressed,None,Moderate,Mild,None,None,Mild,Mild,None,Normal,1

In [122]:
# Creating features set
X = df2.drop(columns='is_4dx_tested')
X = pd.get_dummies(X)
X.head()

,age,weight_lbs,temperature,heart_rate_bpm,resp_rate_bpm,mm_Light Pink,mm_Pale,mm_Pink,crt_1-2 sec,crt_<1 sec,...,joint_swelling_Mild,joint_swelling_Moderate,joint_swelling_None,reported_weight_loss_None,reported_weight_loss_Present,skin_condition_Bruising,skin_condition_Irritation,skin_condition_Normal,skin_condition_Petechia,skin_condition_Petechiae
6,1.000000,15,102,183,44,0,0,1,1,0,...,0,0,1,1,0,0,0,1,0,0
8,2.000000,72,100,138,21,0,0,1,0,0,...,0,0,1,0,1,0,0,1,0,0
10,0.005479,63,102,160,50,0,0,1,1,0,...,0,0,1,1,0,0,0,1,0,0
11,0.005479,59,102,157,18,0,0,1,0,0,...,1,0,0,1,0,0,0,1,0,0
19,6.000000,42,104,110,40,1,0,0,1,0,...,1,0,0,1,0,0,0,1,0,0

In [123]:
#Define the Target Set
y = df2['is_4dx_tested'].ravel()
y[:5]

array([0, 0, 0, 0, 1])

In [124]:
# Splitting into Train and Test sets.
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [125]:
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [126]:
from sklearn.ensemble import RandomForestClassifier
# Create a random forest classifier.
rf_model = RandomForestClassifier(n_estimators=500, random_state=78)

In [127]:
# Fitting the model
rf_model = rf_model.fit(X_train_scaled, y_train)

In [128]:
# Making predictions using the testing data.
predictions = rf_model.predict(X_test_scaled)
predictions

array([0, 0, 0, ..., 0, 0, 0])

In [147]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
# Calculating the accuracy score.
acc_score = accuracy_score(y_test, predictions)
acc_score

1.0

In [148]:
# Calculating the confusion matrix.
cm = confusion_matrix(y_test, predictions)

# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual Negative", "Actual Positive"],columns=["Predicted Negative", "Predicted Positive"])

cm_df

                 Predicted Negative  Predicted Positive
Actual Negative                3721                   0
Actual Positive                   0                 524

In [149]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix

                 Predicted Negative  Predicted Positive
Actual Negative                3721                   0
Actual Positive                   0                 524

Accuracy Score : 1.0
Classification Report
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3721
           1       1.00      1.00      1.00       524

    accuracy                           1.00      4245
   macro avg       1.00      1.00      1.00      4245
weighted avg       1.00      1.00      1.00      4245

In [150]:
# Calculate feature importance in the Random Forest model.
importances = rf_model.feature_importances_
importances

array([4.64425487e-03, 5.52722163e-03, 3.65565281e-01, 5.92378816e-03,
       5.62955874e-03, 8.21319468e-04, 6.25821897e-04, 8.50351762e-04,
       1.12430733e-03, 9.03609617e-04, 8.80050493e-04, 6.31859765e-04,
       1.39376767e-04, 2.26513310e-03, 1.25897679e-02, 1.77700717e-05,
       2.22161674e-03, 3.81970479e-04, 1.16290173e-03, 6.22109670e-04,
       1.14963519e-03, 2.91670733e-04, 1.12081390e-03, 5.73007992e-04,
       1.09934338e-03, 4.03200284e-03, 7.08327973e-04, 7.73519632e-03,
       3.77629835e-03, 3.15194028e-03, 1.13813248e-03, 7.86473738e-03,
       8.45925406e-02, 8.43329923e-02, 9.96817163e-03, 1.17051855e-01,
       5.46155147e-02, 7.21726925e-03, 9.73975031e-02, 3.70349100e-02,
       2.09368421e-02, 1.98337046e-02, 1.58111050e-03, 3.14658630e-04,
       4.80398053e-03, 1.50721580e-02, 7.76107495e-05])

In [160]:
# We can sort the features by their importance.
sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

[(0.36556528114583775, 'temperature'),
 (0.11705185509758301, 'muscle_pain_Moderate'),
 (0.0973975031319296, 'joint_swelling_Moderate'),
 (0.08459254056636778, 'lameness_None'),
 (0.08433299233440672, 'lameness_Present'),
 (0.054615514744712886, 'muscle_pain_None'),
 (0.03703490996249265, 'joint_swelling_None'),
 (0.020936842091399926, 'reported_weight_loss_None'),
 (0.019833704609097915, 'reported_weight_loss_Present'),
 (0.015072158049482986, 'skin_condition_Petechia'),
 (0.012589767870752302, 'mentation_Dull/Depressed'),
 (0.009968171634448585, 'muscle_pain_Mild'),
 (0.0078647373816248, 'lethargic_None'),
 (0.007735196324573669, 'inappetence_None'),
 (0.007217269254722422, 'joint_swelling_Mild'),
 (0.0059237881625626935, 'heart_rate_bpm'),
 (0.005629558736415917, 'resp_rate_bpm'),
 (0.005527221631881471, 'weight_lbs'),
 (0.004803980532737194, 'skin_condition_Normal'),
 (0.004644254866274592, 'age'),
 (0.004032002839329968, 'inappetence_Mild'),
 (0.003776298349883266, 'inappetence_Severe'),
 (0.003151940275866941, 'lethargic_Mild'),
 (0.0022651330982079577, 'mentation_BAR'),
 (0.002221616740315751, 'mentation_QAR'),
 (0.001581110499728336, 'skin_condition_Bruising'),
 (0.0011629017276879531, 'vomiting_Mild'),
 (0.0011496351923657693, 'vomiting_None'),
 (0.0011381324759701006, 'lethargic_Moderate'),
 (0.0011243073282334527, 'crt_1-2 sec'),
 (0.001120813898905909, 'diarrhea_Mild'),
 (0.0010993433765994949, 'diarrhea_None'),
 (0.0009036096171470081, 'crt_<1 sec'),
 (0.0008800504929256399, 'crt_>2 sec'),
 (0.0008503517620949481, 'mm_Pink'),
 (0.0008213194675358192, 'mm_Light Pink'),
 (0.0007083279730210333, 'inappetence_Moderate'),
 (0.0006318597653784581, 'crt_UTO'),
 (0.0006258218972599138, 'mm_Pale'),
 (0.000622109670094473, 'vomiting_Moderate'),
 (0.0005730079918097138, 'diarrhea_Moderate'),
 (0.0003819704793787611, 'vomiting_Chronic'),
 (0.00031465863040150004, 'skin_condition_Irritation'),
 (0.00029167073250873016, 'diarrhea_Chronic'),
 (0.00013937676685776243, 'mentation_Anxious/Agitated'),
 (7.761074947238408e-05, 'skin_condition_Petechiae'),
 (1.7770071714241846e-05, 'mentation_Obtunded')]